### ISSUE TITLE
Contenedor truena porque start.sh no instala dependencias

### ISSUE THREAD

**Issue by rodowi** [mxabierto/sara#112]
o porque el PIP folder no es del usuario:

```bash
The temporary folder for building (/tmp/pip_build_root) is either not owned by you, or is a symlink.
pip will not work until the temporary folder is either deleted or is a real directory owned by your user account.
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 73, in <module>
    from pip.util import get_installed_distributions, get_prog
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 16, in <module>
    from pip.locations import (site_packages, running_under_virtualenv, virtualenv_no_global,
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 96, in <module>
    build_prefix = _get_build_prefix()
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 87, in _get_build_prefix
    raise pip.exceptions.InstallationError(msg)
pip.exceptions.InstallationError: The temporary folder for building (/tmp/pip_build_root) is either not owned by you, or is a symlink.
/root/sara/start.sh: line 18: celery: command not found
Traceback (most recent call last):
  File "./create_recommendations.py", line 4, in <module>
    from elasticsearch import Elasticsearch,helpers
ImportError: No module named elasticsearch
Traceback (most recent call last):
  File "./ml_classifier.py", line 4, in <module>
    from flask import Flask, request, jsonify, make_response, abort, g, url_for
ImportError: No module named flask
```

**Comment by rodowi** [comment]
```bash
➜  sara git:(master) ✗ ls -l db 
total 8
drwxr-xr-x   3 rodowi  staff   102 Aug  6 17:05 pip_build_root
```

**Comment by rodowi** [comment]
tal vez es porque el build pasado creó el directorio en el host, y el nuevo container encontró que ya existía el folder donde quiere temporalmente hacer las operaciones de PIP

Puede que esto lo resuelva
```bash
➜  sara git:(master) ✗ rm -r db/pip_build_root 
➜  sara git:(master) ✗ docker rm e313
➜  sara git:(master) ✗ docker run ... mxabierto/sara
```

**Comment by rodowi** [comment]
si ves esto, significa que hay éxito

```bash
 66200K .......... .......... .......... .......... .......... 99% 51.4M 0s
 66250K .........                                             100%  107M=10s

2015-08-06 23:43:36 (6.17 MB/s) - 'model-0.1.tgz' saved [67849659/67849659]

Ignoring indexes: https://pypi.python.org/simple/
Unpacking /tmp/wheel-aA399/Flask-0.10.1-py2-none-any.whl
```

**Comment by rodowi** [comment]
éxito

```bash
➜  sara git:(master) ✗ curl http://`boot2docker ip`:5000/recommendations\?title\=foo
{"results": []}%  
```
