### ISSUE TITLE
Implementar task manager ( celery ) para clasificación de solicitudes

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/sara#21]
Installing collected packages: celery, billiard, kombu, redis, amqp, anyjson
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 214, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 204, in clobber
    os.makedirs(destdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/celery-3.1.18.dist-info'

Storing debug log for failure in /home/vagrant/.pip/pip.log

**Comment by rodowi** [comment]
nevermind, son temas de vagrant

**Comment by rodowi** [comment]
Hay que agregar a Vagrant:

celery -A tasks worker --loglevel=info

**Comment by rodowi** [comment]
E instalar redis

cd /usr/local/lib
wget http://download.redis.io/redis-stable.tar.gz
tar xvzf redis-stable.tar.gz
cd redis-stable
make
redis-server

**Comment by rodowi** [comment]
vagrant@debian-800-jessie:/vagrant$ /usr/local/bin/redis-stable/src/redis-server  &

**Comment by rodowi** [comment]
Como eval regresa AsyncResult, ya no lo podemos incluir en la respuesta al usuario
  File "/vagrant/ml_classifier.py", line 98, in create_task
    'classification_id': myeval[0]}), 201
TypeError: 'AsyncResult' object does not support indexing

**Comment by rodowi** [comment]
About to be closed by #44
