### ISSUE TITLE
Elasticsearch no se levanta en Vagrant

### ISSUE THREAD

**Issue by rodowi** [mxabierto/sara#68]
En development, Vagrant lo instala en:

`$ ls /usr/share/`

Pero falta definir el path de Java:

```
vagrant@debian-800-jessie:~$ /usr/share/elasticsearch/bin/elasticsearch
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME
vagrant@debian-800-jessie:~$ which java
vagrant@debian-800-jessie:~$ 
```

**Comment by rodowi** [comment]
@urkonn el provisioning agrega java?

**Comment by rodowi** [comment]
Necesitamos instalar el JDK no?

https://github.com/Traackr/ansible-elasticsearch/blob/master/tasks/main.yml#L16

**Comment by rodowi** [comment]
Después de agregar JDK (sin settear aún la env var), sigue fallando ES

```
vagrant@debian-800-jessie:~$ /usr/share/elasticsearch/bin/elasticsearch
Failed to configure logging...
org.elasticsearch.ElasticsearchException: Failed to load logging configuration
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:142)
```

**Comment by rodowi** [comment]
Agregando el config aún falta permiso en /data

	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data

**Comment by rodowi** [comment]
Lo más fácil será que el elasticsearch user y group sean vagrant:vagrant

**Comment by rodowi** [comment]
Falta el logger nadamás:

vagrant@debian-800-jessie:~$ /usr/share/elasticsearch/bin/elasticsearch
Failed to configure logging...
org.elasticsearch.ElasticsearchException: Failed to load logging configuration
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:142)

**Comment by rodowi** [comment]
Ya. Tenía permisos de root. Así que le agregué un:

```
- file: path={{ elasticsearch_conf_dir }}/logging.yml owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0644
```

**Comment by rodowi** [comment]
MOTHERFKKKKKKR

vagrant@debian-800-jessie:~$ /usr/share/elasticsearch/bin/elasticsearch
-bash: /usr/share/elasticsearch/bin/elasticsearch: Permission denied
vagrant@debian-800-jessie:~$ sudo ls -l /usr/share/elasticsearch/bin/elasticsearch
-rwxr-xr-x 1 vagrant vagrant 8115 Jun  9 13:38 /usr/share/elasticsearch/bin/elasticsearch

**Comment by rodowi** [comment]
No entiendo por qué tengo errores de permisos si todo es para el usuario vagrant


vagrant@debian-800-jessie:~$ ls -l /usr/share/elasticsearch/
ls: cannot access /usr/share/elasticsearch/lib: Permission denied
ls: cannot access /usr/share/elasticsearch/README.textile: Permission denied
ls: cannot access /usr/share/elasticsearch/NOTICE.txt: Permission denied
ls: cannot access /usr/share/elasticsearch/bin: Permission denied
ls: cannot access /usr/share/elasticsearch/plugins: Permission denied
ls: cannot access /usr/share/elasticsearch/data: Permission denied
total 0
d????????? ? ? ? ?            ? bin
d????????? ? ? ? ?            ? data
d????????? ? ? ? ?            ? lib
-????????? ? ? ? ?            ? NOTICE.txt
d????????? ? ? ? ?            ? plugins
-????????? ? ? ? ?            ? README.textile
vagrant@debian-800-jessie:~$ sudo ls -l /usr/share/elasticsearch/
total 32
drw-r--r-- 2 vagrant vagrant 4096 Jun 29 16:29 bin
drw-r--r-- 2 vagrant vagrant 4096 Jun 29 18:31 data
drw-r--r-- 3 vagrant vagrant 4096 Jun 29 16:29 lib
-rw-r--r-- 1 vagrant vagrant  150 Jun  9 13:38 NOTICE.txt
drw-r--r-- 2 vagrant vagrant 4096 Jun  9 13:38 plugins
-rw-r--r-- 1 vagrant vagrant 8700 Jun  9 13:38 README.textile

**Comment by rodowi** [comment]
superseded by docker
