### ISSUE TITLE
El worker de evaluate_petition se rompe

### ISSUE THREAD

**Issue by rodowi** [mxabierto/sara#92]
```bash
➜  sara git:(86-PUT-exceptions) ✗ docker exec 89ec tail -f /logs/sara-celery.log
[2015-07-29 19:40:58,635: INFO/MainProcess] Received task: tasks.evaluate_petition[88d8465e-9945-4b70-903a-3c4ec680fbac]
[2015-07-29 19:40:58,638: INFO/MainProcess] Received task: tasks.catch_bad_words_in_text[4539838c-1800-4616-8c94-e487f251f323]
[2015-07-29 19:40:58,659: WARNING/Worker-1] {u'vivienda': 0, u'el': 0, u'de': 0, u'para': 0, u'material': 0, u'construccion': 0, u'su': 0, u'apoyo': 0, u'mejoramiento': 0, u'con': 0}
[2015-07-29 19:40:58,670: INFO/MainProcess] Task tasks.catch_bad_words_in_text[4539838c-1800-4616-8c94-e487f251f323] succeeded in 0.0297197149994s: {'profanity_score': 0, 'text': u'apoyo con material de construcci\xf3n para el mejoramiento de su vivienda'}
[2015-07-29 19:43:12,840: ERROR/MainProcess] Process 'Worker-3' pid:42 exited with 'signal 9 (SIGKILL)'
[2015-07-29 19:43:12,872: ERROR/MainProcess] Task tasks.evaluate_petition[88d8465e-9945-4b70-903a-3c4ec680fbac] raised unexpected: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1171, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
```

siguiendo las instrucciones de 
https://github.com/mxabierto/sara/wiki/Deployment

**Comment by iorch** [comment]
Yo no reproduzco esto. Puese mal un URL, y no se rompe el proceso, pero si indica que no se obtuvo un 200:

```
[2015-07-29 20:59:30,246: INFO/MainProcess] Received task: tasks.update_remote_petition[4f985e58-e681-4cfe-8cc3-6e94573c15c5]
[2015-07-29 20:59:30,248: INFO/MainProcess] Task tasks.catch_bad_words_in_text[cc14a812-7caf-445c-b912-d5bfff551907] succeeded in 0.52544303899s: {'profanity_score': 1, 'text': u'Quisiera ue me dieran un prestamo para comprar una casita o un departamento del infonavit,...
[2015-07-29 20:59:30,311: INFO/Worker-1] Starting new HTTP connection (1): www.gob.mx
[2015-07-29 20:59:31,217: WARNING/Worker-1] Updating:
[2015-07-29 20:59:31,218: WARNING/Worker-1] {"text": "Quisiera ue me dieran un prestamo para comprar una casita o un departamento del infonavit, porque necesito una vivienda digna, y no la pinche pocilga en la que vivo", "agency": 28, "id": "1", "proceeds": {"reason": "Petici?n Irrespetuosa", "value": false}}
[2015-07-29 20:59:31,218: WARNING/Worker-1] PUT request to
[2015-07-29 20:59:31,220: WARNING/Worker-1] http://www.gob.mx/SAC/petitionClassifier/updates
[2015-07-29 20:59:31,221: WARNING/Worker-1] was
[2015-07-29 20:59:31,221: WARNING/Worker-1] 502
[2015-07-29 20:59:31,222: INFO/MainProcess] Task tasks.update_remote_petition[4f985e58-e681-4cfe-8cc3-6e94573c15c5] succeeded in 0.973499588988s: None
```
lo que sí noto es que tiene probleas con la impresión de utf8

**Comment by rodowi** [comment]
hiciste de nuevo el docker build y el deploy del contenedor? estas usando la versión de código más nueva?

**Comment by iorch** [comment]
sí, y copié y pegué el yml que viene en las instrucciones del deployment para docker compose.
Creo que en el docker-compose.yml de master falta la linea 
`- /home/core/sara/volumes/db:/tmp/`
en los volumenes de sara

**Comment by rodowi** [comment]
en qué app? elasticsearch? las otras ya tienen volumen

**Comment by iorch** [comment]
en sara, en el wiki tenemos 

```yml
sara:
  image: mxabierto/sara
  ports:
    - "5000:5000"
  volumes:
    - /home/core/sara/logs:/logs
    - /home/core/sara/volumes/db:/tmp/
  environment:
    - SQLALCHEMY_URL=sqlite:////tmp/users.db
    - SECRET_KEY="supersecret"
    - DEBUG_MODE=False
    - SARA_MODEL=https://s3.amazonaws.com/org.mxabierto/sara/model-0.1.tgz
    - PETITIONS_SERVER_URL=x.x.x.x
  links:
    - elasticsearch
    - redis
    - mysql
```

mientras que en master

```yml
sara:
  image: mxabierto/sara
  ports:
    - "5000:5000"
  volumes:
    - /home/core/sara/logs:/logs
  environment:
    - SARA_MODEL=https://s3.amazonaws.com/org.mxabierto/sara/model-0.1.tgz
    - PETITIONS_SERVER_URL=http://example.com/update
    - SQLALCHEMY_URL=sqlite:////tmp/users.db
    - SECRET_KEY=HACKME
  links:
    - elasticsearch
    - redis
    - mysql
```

**Comment by rodowi** [comment]
ya no me está fallando, no se que pasó

seguro son locuras el boot2docker

**Comment by rodowi** [comment]
o de nuestro docker-compose.yml

**Comment by rodowi** [comment]
➜  sara git:(exceptions-plus-fix-compose) ✗ docker exec 4d86 tail -f /logs/sara-celery.log 
[2015-07-30 16:32:43,206: INFO/MainProcess] Received task: tasks.evaluate_petition[2a8b13de-8660-43c3-8fb8-2e5456fcab76]
[2015-07-30 16:32:43,209: INFO/MainProcess] Received task: tasks.catch_bad_words_in_text[fe669a77-15e6-44d9-8c01-86c8a8cade23]
[2015-07-30 16:32:43,234: WARNING/Worker-4] {u'una': 0, u'beca': 0, u'cocina': 0, u'para': 0, u'estudiar': 0}
[2015-07-30 16:32:43,259: INFO/MainProcess] Task tasks.catch_bad_words_in_text[fe669a77-15e6-44d9-8c01-86c8a8cade23] succeeded in 0.0458105449943s: {'profanity_score': 0, 'text': u'una beca para estudiar cocina'}
[2015-07-30 16:35:11,634: ERROR/MainProcess] Process 'Worker-1' pid:41 exited with 'signal 9 (SIGKILL)'
[2015-07-30 16:35:11,658: ERROR/MainProcess] Task tasks.evaluate_petition[2a8b13de-8660-43c3-8fb8-2e5456fcab76] raised unexpected: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1171, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).

**Comment by rodowi** [comment]
http://celery.readthedocs.org/en/latest/reference/celery.exceptions.html

**Comment by rodowi** [comment]
De hecho, por lo que veo, el worker se queda ciclado y llega hasta un timeout:

```
[2015-07-30 16:39:52,553: INFO/MainProcess] Received task: tasks.evaluate_petition[26ce0abd-8454-4b4c-a4ce-772ab6b0c73d]
[2015-07-30 16:39:52,556: INFO/MainProcess] Received task: tasks.catch_bad_words_in_text[7e592f22-a891-43f1-bd74-74f604dbcc30]
[2015-07-30 16:39:52,570: WARNING/Worker-2] {u'una': 0, u'beca': 0, u'cocina': 0, u'para': 0, u'estudiar': 0}
[2015-07-30 16:39:52,578: INFO/MainProcess] Task tasks.catch_bad_words_in_text[7e592f22-a891-43f1-bd74-74f604dbcc30] succeeded in 0.0195595929981s: {'profanity_score': 0, 'text': u'una beca para estudiar cocina'}

[2015-07-30 16:45:03,641: ERROR/MainProcess] Process 'Worker-5' pid:66 exited with 'signal 9 (SIGKILL)'
[2015-07-30 16:45:03,667: ERROR/MainProcess] Task tasks.evaluate_petition[26ce0abd-8454-4b4c-a4ce-772ab6b0c73d] raised unexpected: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1171, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
```

Lo que no entiendo es por qué no da entonces un [TimeoutError](http://celery.readthedocs.org/en/latest/reference/celery.exceptions.html#celery.exceptions.TimeoutError)


La petición llega en:
[2015-07-30 16:39:52,553: INFO/MainProcess] Received task: tasks.evaluate_petition[26ce0abd-8454-4b4c-a4ce-772ab6b0c73d]
La excepción se lanza en:
[2015-07-30 16:45:03,667: ERROR/MainProcess] Task tasks.evaluate_petition[26ce0abd-8454-4b4c-a4ce-772ab6b0c73d] raised unexpected: WorkerLostError('Worker exited prematurely: signal 9

**Comment by rodowi** [comment]
UPDATE:

Le agregué un print statement antes del return del else
https://github.com/mxabierto/sara/pull/95/files#diff-dc31105b816206de63c47bf42ec2a4d7R33

y no se ve en el log,

parece que WorkerLostError no la puede cachar nuestro código... es como si hubiera un sys.exit en alguna de las funciones del clasificador que se invocan en L23-27
https://github.com/mxabierto/sara/pull/95/files#diff-dc31105b816206de63c47bf42ec2a4d7R23

**Comment by rodowi** [comment]
Será porque tenía 2 containers de redis en el mismo puerto :neckbeard: ?

➜  sara git:(99-token-shall-remain) ✗ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                                              NAMES
52657d17bb04        redis               "/entrypoint.sh redi   3 days ago          Up 3 days           0.0.0.0:32818->6379/tcp                            docker_redis_1         
d89418ee5609        mysql               "/entrypoint.sh mysq   4 days ago          Up 4 days           0.0.0.0:32813->3306/tcp                            sara_mysql_1           
9f14790ee859        redis               "/entrypoint.sh redi   4 days ago          Up 4 days           0.0.0.0:32812->6379/tcp                            sara_redis_1           
27475b7ef121        elasticsearch       "/docker-entrypoint.   4 days ago          Up 4 days           0.0.0.0:32811->9200/tcp, 0.0.0.0:32810->9300/tcp   sara_elasticsearch_1

**Comment by rodowi** [comment]
ya no me sucede

**Comment by rodowi** [comment]
Jaló el primero

```bash
[2015-08-06 23:53:24,206: INFO/MainProcess] Task tasks.evaluate_petition[de20e1c9-d669-4d33-9e3a-66b51071e484] succeeded in 19.981417154s: {'agency': 0, 'id': u'201412015PMGMQ'}
[2015-08-06 23:53:24,485: INFO/Worker-2] Starting new HTTP connection (1): example.com
[2015-08-06 23:53:30,483: WARNING/Worker-2] Updating:
[2015-08-06 23:53:30,486: WARNING/Worker-2] {"text": "apoyo con material de construcci?n para el mejoramiento de su vivienda", "agency": 0, "id": "201412015PMGMQ", "proceeds": {"value": true}}
[2015-08-06 23:53:30,487: WARNING/Worker-2] PUT request to
[2015-08-06 23:53:30,488: WARNING/Worker-2] http://example.com/update
[2015-08-06 23:53:30,488: WARNING/Worker-2] was
[2015-08-06 23:53:30,489: WARNING/Worker-2] 502
[2015-08-06 23:53:30,490: WARNING/Worker-2] HTTP ERROR occured, status code 502
[2015-08-06 23:53:30,490: WARNING/Worker-2] ERROR reason: Bad Gateway
[2015-08-06 23:53:30,491: WARNING/Worker-2] 502 Server Error: Bad Gateway
[2015-08-06 23:53:30,510: INFO/MainProcess] Task tasks.update_remote_petition[a1c45666-493e-4648-95c6-49a80c267902] succeeded in 6.255711402s: None
```

falló el segundo

```
[2015-08-06 23:54:05,619: INFO/MainProcess] Received task: tasks.evaluate_petition[77ecd3ff-93b3-41e7-b14e-ce26c5594d20]
[2015-08-06 23:54:05,622: INFO/MainProcess] Received task: tasks.catch_bad_words_in_text[3d1c3425-6d58-4886-a5e0-d0caf14ab727]
[2015-08-06 23:54:05,660: WARNING/Worker-3] {u'rolense': 0, u'beca': 0, u'una': 0}
[2015-08-06 23:54:05,676: INFO/MainProcess] Task tasks.catch_bad_words_in_text[3d1c3425-6d58-4886-a5e0-d0caf14ab727] succeeded in 0.0493980270003s: {'profanity_score': 0, 'text': u'rolense una beca'}
[2015-08-06 23:54:38,260: ERROR/MainProcess] Process 'Worker-4' pid:41 exited with 'signal 9 (SIGKILL)'
[2015-08-06 23:54:38,365: ERROR/MainProcess] Task tasks.evaluate_petition[77ecd3ff-93b3-41e7-b14e-ce26c5594d20] raised unexpected: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1171, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).

```

**Comment by rodowi** [comment]
En la tercera clasificación habla de unicode

```bash
[2015-08-06 23:56:06,211: INFO/MainProcess] Received task: tasks.evaluate_petition[9a1a6933-d916-4123-b99b-b2e75d75631d]
[2015-08-06 23:56:06,216: INFO/MainProcess] Received task: tasks.catch_bad_words_in_text[31f7f727-7363-478d-9def-c277bc415ced]
[2015-08-06 23:56:06,514: WARNING/Worker-2] {u'vivienda': 0, u'el': 0, u'de': 0, u'para': 0, u'material': 0, u'construccion': 0, u'su': 0, u'apoyo': 0, u'mejoramiento': 0, u'con': 0}
[2015-08-06 23:56:06,541: WARNING/Worker-2] /usr/local/lib/python2.7/dist-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: UnicodeDecodeError('ascii', '\x80\x02}q\x01(U\x06statusq\x02U\x07SUCCESSq\x03U\ttracebackq\x04NU\x06resultq\x05}q\x06(U\x0fprofanity_scoreq\x07K\x00U\x04textq\x08XG\x00\x00\x00apoyo con material de construcci\xc3\xb3n para el mejoramiento de su viviendaq\tuU\x08childrenq\n]u.', 0, 1, 'ordinal not in range(128)'):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 490, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 160, in set
    return self.ensure(self._set, (key, value), **retry_policy)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 149, in ensure
    **retry_policy
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 243, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 169, in _set
    pipe.execute()
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2465, in _execute_transaction
    self.annotate_exception(ex, i + 1, command[0])
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2529, in annotate_exception
    cmd = unicode(' ').join(imap(unicode, command))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

  exc, exc_info.traceback)))
[2015-08-06 23:56:06,557: CRITICAL/MainProcess] Task tasks.catch_bad_words_in_text[31f7f727-7363-478d-9def-c277bc415ced] INTERNAL ERROR: UnicodeDecodeError('ascii', '\x80\x02}q\x01(U\x06statusq\x02U\x07SUCCESSq\x03U\ttracebackq\x04NU\x06resultq\x05}q\x06(U\x0fprofanity_scoreq\x07K\x00U\x04textq\x08XG\x00\x00\x00apoyo con material de construcci\xc3\xb3n para el mejoramiento de su viviendaq\tuU\x08childrenq\n]u.', 0, 1, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 490, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 160, in set
    return self.ensure(self._set, (key, value), **retry_policy)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 149, in ensure
    **retry_policy
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 243, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 169, in _set
    pipe.execute()
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2465, in _execute_transaction
    self.annotate_exception(ex, i + 1, command[0])
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2529, in annotate_exception
    cmd = unicode(' ').join(imap(unicode, command))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)
[2015-08-06 23:56:07,376: ERROR/MainProcess] Unrecoverable error: ResponseError('MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/dist-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/dist-packages/kombu/async/hub.py", line 324, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 950, in on_readable
    item = self.cycle.on_readable(fileno)
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 322, in on_readable
    return chan.handlers[type]()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/redis.py", line 619, in _brpop_read
    **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 574, in read_response
    raise response
ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
[2015-08-06 23:56:21,808: WARNING/Worker-1] /usr/local/lib/python2.7/dist-packages/celery/app/trace.py:365: RuntimeWarning: Exception raised outside body: UnicodeDecodeError('ascii', '\x80\x02}q\x01(U\x06statusq\x02U\x07SUCCESSq\x03U\ttracebackq\x04NU\x06resultq\x05}q\x06(U\x06agencyq\x07cnumpy.core.multiarray\nscalar\nq\x08cnumpy\ndtype\nq\tU\x02i8K\x00K\x01\x87Rq\n(K\x03U\x01<NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tbU\x08\x00\x00\x00\x00\x00\x00\x00\x00\x86Rq\x0bU\x02idq\x0cX\x0e\x00\x00\x00201412015PMGMQq\ruU\x08childrenq\x0e]u.', 0, 1, 'ordinal not in range(128)'):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 490, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 160, in set
    return self.ensure(self._set, (key, value), **retry_policy)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 149, in ensure
    **retry_policy
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 243, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 169, in _set
    pipe.execute()
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2465, in _execute_transaction
    self.annotate_exception(ex, i + 1, command[0])
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2529, in annotate_exception
    cmd = unicode(' ').join(imap(unicode, command))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

  exc, exc_info.traceback)))
[2015-08-06 23:56:22,021: CRITICAL/MainProcess] Task tasks.evaluate_petition[9a1a6933-d916-4123-b99b-b2e75d75631d] INTERNAL ERROR: UnicodeDecodeError('ascii', '\x80\x02}q\x01(U\x06statusq\x02U\x07SUCCESSq\x03U\ttracebackq\x04NU\x06resultq\x05}q\x06(U\x06agencyq\x07cnumpy.core.multiarray\nscalar\nq\x08cnumpy\ndtype\nq\tU\x02i8K\x00K\x01\x87Rq\n(K\x03U\x01<NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tbU\x08\x00\x00\x00\x00\x00\x00\x00\x00\x86Rq\x0bU\x02idq\x0cX\x0e\x00\x00\x00201412015PMGMQq\ruU\x08childrenq\x0e]u.', 0, 1, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 283, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 256, in store_result
    request=request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 490, in _store_result
    self.set(self.get_key_for_task(task_id), self.encode(meta))
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 160, in set
    return self.ensure(self._set, (key, value), **retry_policy)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 149, in ensure
    **retry_policy
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 243, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/redis.py", line 169, in _set
    pipe.execute()
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2578, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2465, in _execute_transaction
    self.annotate_exception(ex, i + 1, command[0])
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2529, in annotate_exception
    cmd = unicode(' ').join(imap(unicode, command))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

```

**Comment by rodowi** [comment]
Los errores que se ven son:

[2015-08-06 23:56:07,376: ERROR/MainProcess] Unrecoverable error: ResponseError('MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',)
Traceback (most recent call last):

y

UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

**Comment by rodowi** [comment]
Mi primera sospecha sería que tuviera redis en el host,
```bash
➜  sara git:(master) ✗ redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
pero de todas maneras boot2docker corre en otro ip

**Comment by rodowi** [comment]
jaló con "quiero una beca"

"quiero un pastel" rompió el worker

**Comment by rodowi** [comment]
parece que es el mismo escalamiento, la primera funciona, la segunda tira problemas en el worker, y el tercero el tema de REDIS

**Comment by rodowi** [comment]
http://stackoverflow.com/questions/19581059/misconf-redis-is-configured-to-save-rdb-snapshots

**Comment by rodowi** [comment]
```bash
➜  sara git:(master) ✗ nc -vz `boot2docker ip` 6379
nc: connectx to 192.168.59.103 port 6379 (tcp) failed: Connection refused
➜  sara git:(master) ✗ nc -vz `boot2docker ip` 5000
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif vboxnet5
	src 192.168.59.3 port 60311
	dst 192.168.59.103 port 5000
	rank info not available
	TCP aux info available

Connection to 192.168.59.103 port 5000 [tcp/commplex-main] succeeded!
➜  sara git:(master) ✗ nc -vz `boot2docker ip` 9200
nc: connectx to 192.168.59.103 port 9200 (tcp) failed: Connection refused
➜  sara git:(master) ✗ nc -vz `boot2docker ip` 3306
nc: connectx to 192.168.59.103 port 3306 (tcp) failed: Connection refused
```

**Comment by rodowi** [comment]
docker logs
```bash
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
No handlers could be found for logger "elasticsearch.trace"
```

Creo que tiene que ver con el --link a los containers

**Comment by rodowi** [comment]
En docker logs veo el UnicodeDecodeError en redis-client.py, y parece que no alcanza a llegar al log de celery

```bash
    self.annotate_exception(ex, i + 1, command[0])
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2529, in annotate_exception
    cmd = unicode(' ').join(imap(unicode, command))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)
```

**Comment by rodowi** [comment]
Ahora se rompe desde el primer request
